general {
    lock_cmd = pidof hyprlock || hyprlock --no-fade-in --immediate-render
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

listener {
    timeout = 360
    on-timeout = niri msg action power-off-monitors
    on-resume = niri msg action power-on-monitors
}
